<SOAP-ENV:Envelope xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:m1="urn:soap.embus.sbc.com" xmlns:m2="http://lightspeed.bbnms.att.com/ordering" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
  <SOAP-ENV:Header>
    <bbnmsOrderHeader:MessageHeader xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:bbnmsOrderHeader="http://lightspeed.bbnms.att.com/header">
      <ns2:WSHeader xmlns:ns2="http://cio.att.com/commonheader/v3">
        <ns2:WSContext>
          <ns2:SourceIPAddress>10.160.249.210</ns2:SourceIPAddress>
        </ns2:WSContext>
        <ns2:WSMessageData>
          <ns2:Timestamp>2008-02-19T10:09:25.0440</ns2:Timestamp>
        </ns2:WSMessageData>
        <ns2:WSEnterpriseLogging>
          <ns2:LoggingKey>TN:342734237</ns2:LoggingKey>
        </ns2:WSEnterpriseLogging>
      </ns2:WSHeader>
      <ns1:WSDiscovery xmlns:ns1="http://aftdiscovery.att.com/header/v1">
        <ns1:name>MQSSL_ESB_J2EEEJB_ON_AIX</ns1:name>
        <ns1:version>
          <ns1:major>3</ns1:major>
          <ns1:minor>0</ns1:minor>
        </ns1:version>
        <ns1:envContext>Y</ns1:envContext>
        <ns1:bindingType>fusionBus</ns1:bindingType>
      </ns1:WSDiscovery>
    </bbnmsOrderHeader:MessageHeader>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <m2:bbnmsOrder>
      <m2:transactionInfo xmlns:bbnmsOrder="http://lightspeed.bbnms.att.com/ordering">
        <m2:transactionId>342734237</m2:transactionId>
        <m2:taskName>${taskName}</m2:taskName>
        <m2:cvoipSdpProvisioningInd>true</m2:cvoipSdpProvisioningInd>
        <m2:order>
          <m2:orderActionInfoList>
            <m2:orderActionInfo>
              <m2:orderNumber>${orderNumber}</m2:orderNumber>
              <m2:orderActionId>${orderNumber}</m2:orderActionId>
              <m2:originalOrderActionId>${origOrderActId}</m2:originalOrderActionId>
              <m2:orderActionType>${orderActionType}</m2:orderActionType>
              <m2:orderActionSubType>${orderActionSubType}</m2:orderActionSubType>
              <m2:orderActionReferenceNumber>${orderNumber}${orderActionReferenceNumber}</m2:orderActionReferenceNumber>
              <m2:orderCreationDate>${orderCreationDate}</m2:orderCreationDate>
              <m2:assignedProductId>34273423</m2:assignedProductId>
              <m2:creationApplication>OMS</m2:creationApplication>
              <m2:bypassReasonCode>NONE</m2:bypassReasonCode>
              <m2:dueDate>${dueDate}</m2:dueDate>
              <m2:appointment>
                <m2:startTime>${apt_start}</m2:startTime>
                <m2:endTime>${apt_end}</m2:endTime>
              </m2:appointment>
              <m2:orderActionStatus>DE</m2:orderActionStatus>
              <m2:addressInfoList>
                <m2:addressInfo>
                  <m2:addressType>LSBilling</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>123</m2:houseNumber>
                    <m2:streetName>Peachtree</m2:streetName>
                    <m2:streetThoroughfare>ST</m2:streetThoroughfare>
                    <m2:city>Atlanta</m2:city>
                    <m2:state>GA</m2:state>
                    <m2:postalCode>30308</m2:postalCode>
                    <m2:postalCodePlus4>9999</m2:postalCodePlus4>
                    <m2:addressId>${addressId}</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>ShippingFrom</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>123</m2:houseNumber>
                    <m2:streetDirection>NE</m2:streetDirection>
                    <m2:streetName>MAIN</m2:streetName>
                    <m2:streetThoroughfare>ST</m2:streetThoroughfare>
                    <m2:streetNameSuffix>NE</m2:streetNameSuffix>
                    <m2:city>ST. LOUIS</m2:city>
                    <m2:state>MO</m2:state>
                    <m2:postalCode>63101</m2:postalCode>
                    <m2:postalCodePlus4>0000</m2:postalCodePlus4>
                    <m2:county>ST. LOUIS</m2:county>
                    <m2:country>USA</m2:country>
                    <m2:unitType>APT</m2:unitType>
                    <m2:addressId>${addressId}</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>ServiceFSP</m2:addressType>
                  <m2:primaryNpanxx>${primaryNpanxx}</m2:primaryNpanxx>
                  <#if transportType=='FTTN' || transportType == 'FTTP-GPON'>
                  <m2:clli8>${clli8}</m2:clli8>
</#if>
 <#if transportType=='FTTB-F' || transportType == 'FTTB-C'>
                  <m2:clli8>${clli8}</m2:clli8>
		  <m2:fttbBuildingClli>${fttbBuildingClli}</m2:fttbBuildingClli>           
</#if>
                  <m2:region>${region}</m2:region>
                  <m2:livingUnitAddressId>LS${addressId}</m2:livingUnitAddressId>
                  <m2:rateCenterCode>${rateCenterCode}</m2:rateCenterCode>
                  <m2:vhoCode>${vhoCode}</m2:vhoCode>
                  <m2:fieldedAddress>
                    <m2:houseNumber>${houseNumber}</m2:houseNumber>
                    <m2:streetName>Peachtree</m2:streetName>
                    <m2:streetThoroughfare>ST</m2:streetThoroughfare>
                    <m2:city>Atlanta</m2:city>
                    <m2:state>GA</m2:state>
                    <m2:postalCode>30308</m2:postalCode>
                    <m2:postalCodePlus4>1234</m2:postalCodePlus4>
                    <m2:county>Fulton</m2:county>
                    <m2:country>USA</m2:country>
                    <m2:structureType>BLDG</m2:structureType>
                    <m2:structureValue>2</m2:structureValue>
                    <m2:levelType>FLR</m2:levelType>
                    <m2:levelValue>1</m2:levelValue>
                    <m2:unitType>APT</m2:unitType>
                    <m2:unitValue>1123</m2:unitValue>
                    <m2:originalStreetDirection>South</m2:originalStreetDirection>
                    <m2:originalStreetNameSuffix>suffix</m2:originalStreetNameSuffix>
                    <m2:cassAddressLines>
                      <m2:addressLine>Alpha Beta</m2:addressLine>
                      <m2:addressLine>${houseNumber} Peachtree ST</m2:addressLine>
                      <m2:addressLine>Atlanta GA  30308-1234</m2:addressLine>
                    </m2:cassAddressLines>
                    <m2:cassAdditionalInfo>String</m2:cassAdditionalInfo>
                    <m2:additionalInfo>String</m2:additionalInfo>
                    <m2:countryCode>String</m2:countryCode>
                    <m2:cityCode>String</m2:cityCode>
                    <m2:serviceLocationName>String</m2:serviceLocationName>
                    <m2:addressId>${addressId}</m2:addressId>
                    <m2:aliasName>String</m2:aliasName>
                    <m2:attention>String</m2:attention>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>ServiceUSPS</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>8000</m2:houseNumber>
                    <m2:streetName>FOREST CROSSING</m2:streetName>
                    <m2:city>LIVE OAK</m2:city>
                    <m2:state>TX</m2:state>
                    <m2:postalCode>78233</m2:postalCode>
                    <m2:postalCodePlus4>4338</m2:postalCodePlus4>
                    <m2:country>USA</m2:country>
                    <m2:cassAddressLines>
                      <m2:addressLine>8000 FOREST CROSSING</m2:addressLine>
                      <m2:addressLine>LIVE OAK,TX 78233 - 4338</m2:addressLine>
                    </m2:cassAddressLines>
                    <m2:addressId>${addressId}</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>OSPBilling</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>8000</m2:houseNumber>
                    <m2:streetName>FOREST CROSSING</m2:streetName>
                    <m2:city>LIVE OAK</m2:city>
                    <m2:state>TX</m2:state>
                    <m2:postalCode>78233</m2:postalCode>
                    <m2:postalCodePlus4>4338</m2:postalCodePlus4>
                    <m2:cassAddressLines>
                      <m2:addressLine>8000 FOREST CROSSING</m2:addressLine>
                      <m2:addressLine>LIVE OAK,TX 78233 - 4338</m2:addressLine>
                    </m2:cassAddressLines>
                    <m2:addressId>${addressId}</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
              </m2:addressInfoList>
              <m2:productList>
                <m2:product>
                  <m2:name>AT&amp;T U-verse</m2:name>
                  <m2:componentList>
                    <m2:component>
                      <m2:assignedProductId>342734230</m2:assignedProductId>
                      <m2:serviceType>UMC</m2:serviceType>
                      <m2:actionIndicator>${umcActInd}</m2:actionIndicator>
                      <m2:attributeList>
                        <m2:attribute>
                          <m2:name>APID</m2:name>
                          <m2:value>342734230</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>versionID</m2:name>
                          <m2:value>1</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>orderActionID</m2:name>
                          <m2:value>342734237</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>customerID</m2:name>
                          <m2:value>101494978</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>serviceID</m2:name>
                          <m2:value>${circuitId}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>relationID</m2:name>
                          <m2:value>2107709</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>UVOrderActionType</m2:name>
                          <m2:value>${uvOrderActionType}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>orderReasonCode</m2:name>
                          <m2:value/>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>managerOverrideInd</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>amssDisplaySequence</m2:name>
                          <m2:value>100</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>amssInstallOption</m2:name>
                          <m2:value>${amssInstallOption}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>installationType</m2:name>
                          <m2:value>${installationType}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>technicianDispatchIndicator</m2:name>
                          <m2:value>${technicianDispatchIndicator}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>AMSS_LinkInd</m2:name>
                          <m2:value>Yahoo_DVR_Link:SDP_Link</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>amssRefresh</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>ADPI_isRequired</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>availableBandwidth</m2:name>
                          <m2:value>30.86</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>bandwidthSource</m2:name>
                          <m2:value>E</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>bandwidthUOM</m2:name>
                          <m2:value>MEGABITS_PER_SECOND</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>chngFrmCsiReason</m2:name>
                          <m2:value>NotApplicable</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>pipeCircuitId</m2:name>
                          <m2:value>${circuitId}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>couponValidationWarning</m2:name>
                          <m2:value>Yes</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>creditCardSecPaid</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>creditCardSecReq</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>NRF_isRequired</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>currentlyUsedBandwidth</m2:name>
                          <m2:value>0.0</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>DefaultDisplayOrder</m2:name>
                          <m2:value>700</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>EligibleForBundleDiscount</m2:name>
                          <m2:value>N</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>fulfillmentIndicator</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>lowProfile</m2:name>
                          <m2:value>N</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>orderDispReason</m2:name>
                          <m2:value>NotApplicable</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>originalavailableBandwidth</m2:name>
                          <m2:value>0.4</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>customerPaidNRF</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>isPortOutToCLEC</m2:name>
                          <m2:value>None</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>preProvisioningIndicator</m2:name>
                          <m2:value>N</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>prepaymentRequired</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>ProductFamily</m2:name>
                          <m2:value>LightSpeed</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>ProdType</m2:name>
                          <m2:value>RG</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>profileLevel</m2:name>
                          <m2:value>Med</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>requestedBandwidth</m2:name>
                          <m2:value>24.6</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>runCreditRules</m2:name>
                          <m2:value>Yes</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>offerSalesMode</m2:name>
                          <m2:value>Lead</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>tosIndicator</m2:name>
                          <m2:value>Y</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>techRequest</m2:name>
                          <m2:value>NA</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>telegenceId</m2:name>
                          <m2:value>${telegenceId}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>totalBandwidth</m2:name>
                          <m2:value>${totalBandwidth}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>nrfType</m2:name>
                          <m2:value>RegularNRF</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>hideComponent</m2:name>
                          <m2:value>Yes</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>inventoryComponentType</m2:name>
                          <m2:value>UMC</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>isSendToTeLS</m2:name>
                          <m2:value>Parent</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>removeComponent</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>completionIndicator</m2:name>
                          <m2:value>${completionIndicator}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>supersedeIndicator</m2:name>
                          <m2:value>NA</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>moveIndicator</m2:name>
                          <m2:value>NA</m2:value>
                        </m2:attribute>
                      </m2:attributeList>
                      <m2:componentList>
                        <m2:component>
                          <m2:assignedProductId>342734231</m2:assignedProductId>
                          <m2:serviceType>PLST</m2:serviceType>
                          <m2:actionIndicator>${plstActInd}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>342734231</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>versionID</m2:name>
                              <m2:value>1</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>relationID</m2:name>
                              <m2:value>2000005</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>amssDisplaySequence</m2:name>
                              <m2:value>2800</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>amssRefresh</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sbcAffiliate</m2:name>
                              <m2:value>LightSpeed</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>availableForSelfInstall</m2:name>
                              <m2:value>NA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>Bandwidth</m2:name>
                              <m2:value>20</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>bandwidthUOM</m2:name>
                              <m2:value>MEGABITS_PER_SECOND</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>CLCI</m2:name>
                              <m2:value>MCXX</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>cingularIndicator</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>DefaultDisplayOrder</m2:name>
                              <m2:value>800</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>EligibleForBundleDiscount</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>LSCircuitId</m2:name>
                              <m2:value>${circuitId}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>NDDRollbackIndicator</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>PrimaryIndForBilling</m2:name>
                              <m2:value>ADL</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProductFamily</m2:name>
                              <m2:value>LightSpeed</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>RG</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>completionIndicator</m2:name>
                              <m2:value>${completionIndicator}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>telegenceId</m2:name>
                              <m2:value>A6MCXX342734237</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>transportType</m2:name>
                              <m2:value>${transportType}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>vpi</m2:name>
                              <m2:value>16</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>vci</m2:name>
                              <m2:value>16</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>tdmTelcoTn</m2:name>
                              <m2:value>4342734237</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>overrideRTIDInd</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>overrideDSLDisconnectTNInd</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>welcomeKit</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>hideComponent</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>inventoryComponentType</m2:name>
                              <m2:value>PLS</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isPortAssigned</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>Child</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>removeComponent</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>transportTypeGroup</m2:name>
                              <m2:value>${transportTypeGroup}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>NA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>LastNadType</m2:name>
                              <m2:value>RG</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>LastTransportPath</m2:name>
                              <m2:value>FTTN</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>17MHzFeature</m2:name>
                              <m2:value>${seventeenMhzFeat}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>original17MHzFeature</m2:name>
                              <m2:value>Disallow</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>vectoringFeature</m2:name>
                              <m2:value>${vectoringFeature}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>originalVectoringFeature</m2:name>
                              <m2:value>Disallow</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isCustomerMigrated</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                          <m2:componentList>
                          <#if orderActionType=='CH'>
						   <m2:component>
                              <m2:assignedProductId>342734232</m2:assignedProductId>
                              <m2:serviceType>RG</m2:serviceType>
							  <m2:actionIndicator>${rgActIndold}</m2:actionIndicator>
                              <m2:attributeList>
                                <m2:attribute>
                                  <m2:name>APID</m2:name>
                                  <m2:value>342734232</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>versionID</m2:name>
                                  <m2:value>1</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>relationID</m2:name>
                                  <m2:value>2000006</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>amssDisplaySequence</m2:name>
                                  <m2:value>2900</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>amssRefresh</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>actualMaterialCode</m2:name>
                                  <m2:value>000000000100000283</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>actualMaterialDescription</m2:name>
                                  <m2:value>Generic RG BOM</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>availableForSelfInstall</m2:name>
                                  <m2:value>NA</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>criticalFullfillment</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>DefaultDisplayOrder</m2:name>
                                  <m2:value>100</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>sapOrderNumber</m2:name>
                                  <m2:value>0002070395</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>sapOrderStatus</m2:name>
                                  <m2:value>Shipped</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>EligibleForBundleDiscount</m2:name>
                                  <m2:value>N</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>fttxInput</m2:name>
                                  <m2:value>FTTX</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>fulfillmentIndicator</m2:name>
                                  <m2:value>Yes</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>installationType</m2:name>
                                  <m2:value>${installationType}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>materialCode</m2:name>
                                  <m2:value>100000610</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>modelNumber</m2:name>
                                  <m2:value>${modelNumberold}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>manufacturer</m2:name>
                                  <m2:value>${manufacturerold}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>USPIndicator</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>internalWAPIndicator</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>NADExist</m2:name>
                                  <m2:value>UNKNOWN</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>rgId</m2:name>
                                  <m2:value>${circuitId}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>NADKitType</m2:name>
                                  <m2:value>UNKNOWN</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>RGReplacementFlag</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <#if transportType=='FTTB-C'>
                                <m2:attribute>
                                  <m2:name>nadType</m2:name>
                                  <m2:value>${nadType1}</m2:value>
                                </m2:attribute>
                                </#if>
                                <#if transportType=='FTTN' || transportType=='FTTP-GPON'>
                                <m2:attribute>
                                  <m2:name>nadType</m2:name>
                                  <m2:value>${nadType}</m2:value>
                                </m2:attribute>
                                </#if>
                                <m2:attribute>
                                  <m2:name>numAtaPorts</m2:name>
                                  <m2:value>2</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>ProdType</m2:name>
                                  <m2:value>RG</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>purchaseTerms</m2:name>
                                  <m2:value>Rent</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>RMA</m2:name>
                                  <m2:value>Y</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>reasonCode</m2:name>
                                  <m2:value>Unknown</m2:value>
                                </m2:attribute>
                                <m2:attribute>
								  <m2:name>recordOnly</m2:name>
								  <m2:value>N</m2:value>
							    </m2:attribute>
                                <m2:attribute>
                                  <m2:name>completionIndicator</m2:name>
                                  <m2:value>${completionIndicator}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>offerSalesMode</m2:name>
                                  <m2:value>Lead</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>shipmentType</m2:name>
                                  <m2:value>NotApplicable</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>shippingDate</m2:name>
                                  <m2:value>2008-10-25T00:00:00</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>shippingIndicator</m2:name>
                                  <m2:value>Tech</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>technicianDispatchIndicator</m2:name>
                                  <m2:value>${technicianDispatchIndicator}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>hideComponent</m2:name>
                                  <m2:value>Yes</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>inventoryComponentType</m2:name>
                                  <m2:value>RG</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>isSendToTeLS</m2:name>
                                  <m2:value>Child</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>removeComponent</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>moveIndicator</m2:name>
                                  <m2:value>NA</m2:value>
                                </m2:attribute>
                              </m2:attributeList>
                            </m2:component>
                            </#if>
                            <m2:component>
                              <m2:assignedProductId>342734232</m2:assignedProductId>
                              <m2:serviceType>RG</m2:serviceType>
                              <m2:actionIndicator>${rgActIndnew}</m2:actionIndicator>
                              <m2:attributeList>
                                <m2:attribute>
                                  <m2:name>APID</m2:name>
                                  <m2:value>342734232</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>versionID</m2:name>
                                  <m2:value>1</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>relationID</m2:name>
                                  <m2:value>2000006</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>amssDisplaySequence</m2:name>
                                  <m2:value>2900</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>amssRefresh</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>actualMaterialCode</m2:name>
                                  <m2:value>000000000100000283</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>actualMaterialDescription</m2:name>
                                  <m2:value>Generic RG BOM</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>availableForSelfInstall</m2:name>
                                  <m2:value>NA</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>criticalFullfillment</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>DefaultDisplayOrder</m2:name>
                                  <m2:value>100</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>sapOrderNumber</m2:name>
                                  <m2:value>0002070395</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>sapOrderStatus</m2:name>
                                  <m2:value>Shipped</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>EligibleForBundleDiscount</m2:name>
                                  <m2:value>N</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>fttxInput</m2:name>
                                  <m2:value>FTTX</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>fulfillmentIndicator</m2:name>
                                  <m2:value>Yes</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>installationType</m2:name>
                                  <m2:value>${installationType}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>primarymaterialCode</m2:name>
                                  <m2:value>100000611</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>primarymodelNumber</m2:name>
                                  <m2:value>${modelNumberold}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>primarymanufacturer</m2:name>
                                  <m2:value>${manufacturerold}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>materialCode</m2:name>
                                  <m2:value>100000610</m2:value>
                                </m2:attribute>
                                <#if orderActionType=='PR'>
                                <m2:attribute>
                                  <m2:name>modelNumber</m2:name>
                                  <m2:value>${modelNumberold}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>manufacturer</m2:name>
                                  <m2:value>${manufacturerold}</m2:value>
                                </m2:attribute>
                                </#if>
                                <#if orderActionType=='CH'>
                                <m2:attribute>
                                  <m2:name>modelNumber</m2:name>
                                  <m2:value>${modelNumbernew}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>manufacturer</m2:name>
                                  <m2:value>${manufacturernew}</m2:value>
                                </m2:attribute>
                                </#if>
                                <m2:attribute>
                                  <m2:name>USPIndicator</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>internalWAPIndicator</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>NADExist</m2:name>
                                  <m2:value>UNKNOWN</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>rgId</m2:name>
                                  <m2:value>${circuitId}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>NADKitType</m2:name>
                                  <m2:value>UNKNOWN</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>RGReplacementFlag</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>nadType</m2:name>
                                  <m2:value>UVRG-X</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>numAtaPorts</m2:name>
                                  <m2:value>2</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>ProdType</m2:name>
                                  <m2:value>RG</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>purchaseTerms</m2:name>
                                  <m2:value>Rent</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>RMA</m2:name>
                                  <m2:value>Y</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>reasonCode</m2:name>
                                  <m2:value>Unknown</m2:value>
                                </m2:attribute>
                                <m2:attribute>
								  <m2:name>recordOnly</m2:name>
								  <m2:value>N</m2:value>
							    </m2:attribute>
                                <m2:attribute>
                                  <m2:name>completionIndicator</m2:name>
                                  <m2:value>${completionIndicator}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>offerSalesMode</m2:name>
                                  <m2:value>Lead</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>shipmentType</m2:name>
                                  <m2:value>NotApplicable</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>shippingDate</m2:name>
                                  <m2:value>2008-10-25T00:00:00</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>shippingIndicator</m2:name>
                                  <m2:value>Tech</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>technicianDispatchIndicator</m2:name>
                                  <m2:value>${technicianDispatchIndicator}</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>hideComponent</m2:name>
                                  <m2:value>Yes</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>inventoryComponentType</m2:name>
                                  <m2:value>RG</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>isSendToTeLS</m2:name>
                                  <m2:value>Child</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>removeComponent</m2:name>
                                  <m2:value>No</m2:value>
                                </m2:attribute>
                                <m2:attribute>
                                  <m2:name>moveIndicator</m2:name>
                                  <m2:value>NA</m2:value>
                                </m2:attribute>
                              </m2:attributeList>
                            </m2:component>
                            <#if wfextActInd??>
							<m2:component>
								<m2:assignedProductId>${orderNumber}8</m2:assignedProductId>
								<m2:serviceType>WFEXT</m2:serviceType>
								<m2:actionIndicator>${wfextActInd}</m2:actionIndicator>
								<m2:attributeList>
									<m2:attribute>
										<m2:name>APID</m2:name>
										<m2:value>${orderNumber}</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>versionID</m2:name>
										<m2:value>0</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>relationID</m2:name>
										<m2:value>89217624</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>moveIndicator</m2:name>
										<m2:value>NA</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>ParentProductType</m2:name>
										<m2:value>RG</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>reasonCode</m2:name>
										<m2:value>Unknown</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>sapOrderStatus</m2:name>
										<m2:value>Unknown</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>purchaseTerms</m2:name>
										<m2:value>Purchase</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>offerSalesMode</m2:name>
										<m2:value>Lead</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>telegenceId</m2:name>
										<m2:value>{telegenceId}</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>criticalFullfillment</m2:name>
										<m2:value>Yes</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>fulfillmentIndicator</m2:name>
										<m2:value>Yes</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>RMA</m2:name>
										<m2:value>Y</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>reShipReason</m2:name>
										<m2:value>NA</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>isSendToTeLS</m2:name>
										<m2:value>Child</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>materialCode</m2:name>
										<m2:value>100003639</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>modelNumber</m2:name>
										<m2:value>4920 AirTies</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>installationType</m2:name>
										<m2:value>${installationType}</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>reShipInd</m2:name>
										<m2:value>N</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>shipmentType</m2:name>
										<m2:value>G</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>pipeCircuitId</m2:name>
										<m2:value>${circuitId}</m2:value>
									</m2:attribute>
									<m2:attribute>
										<m2:name>availableForSelfInstall</m2:name>
										<m2:value>Mandatory</m2:value>
									</m2:attribute>
								</m2:attributeList>
							</m2:component>
							</#if>
                          </m2:componentList>
                        </m2:component>
                        <m2:component>
                          <m2:assignedProductId>342734233</m2:assignedProductId>
                          <m2:serviceType>FL</m2:serviceType>
                          <m2:actionIndicator>${flActInd}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>342734233</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>versionID</m2:name>
                              <m2:value>1</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>relationID</m2:name>
                              <m2:value>2000035</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>amssDisplaySequence</m2:name>
                              <m2:value>3000</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>amssRefresh</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>availableForSelfInstall</m2:name>
                              <m2:value>Automatic</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>DefaultDisplayOrder</m2:name>
                              <m2:value>900</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>completionIndicator</m2:name>
                              <m2:value>${completionIndicator}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>removeComponent</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>None</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>inventoryComponentType</m2:name>
                              <m2:value>WiFi</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>hideComponent</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>wifiIndicator</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>EligibleForBundleDiscount</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>NA</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                        </m2:component>
                        <m2:component>
                          <m2:assignedProductId>342734234</m2:assignedProductId>
                          <m2:serviceType>HSIA</m2:serviceType>
                          <m2:actionIndicator>${hsiaActInd}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>342734234</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>versionID</m2:name>
                              <m2:value>1</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>relationID</m2:name>
                              <m2:value>2107710</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>amssDisplaySequence</m2:name>
                              <m2:value>200</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>availableForSelfInstall</m2:name>
                              <m2:value>NA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>DefaultDisplayOrder</m2:name>
                              <m2:value>200</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>criticalFullfillment</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>compStatus</m2:name>
                              <m2:value>AC</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>componentBandwidth</m2:name>
                              <m2:value>1.0</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>pipeCircuitId</m2:name>
                              <m2:value>${circuitId}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>installationType</m2:name>
                              <m2:value>${installationType}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ipAddressType</m2:name>
                              <m2:value>Dynamic</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>EligibleForBundleDiscount</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>eligibleForPrepayment</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderStatus</m2:name>
                              <m2:value>Unknown</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>questionCsrCsiShipmentType</m2:name>
                              <m2:value>NA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shipmentType</m2:name>
                              <m2:value>NotApplicable</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>completionIndicator</m2:name>
                              <m2:value>${completionIndicator}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>modifiedIndicator</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>SbpValue</m2:name>
                              <m2:value>0</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>RMA</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>purchaseTerms</m2:name>
                              <m2:value>Purchase</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>removeComponent</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>StandAlone</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>inventoryComponentType</m2:name>
                              <m2:value>HSIA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>hideComponent</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>welcomeKit</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>uverseTechnology</m2:name>
                              <m2:value>PLS</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>termsAcceptance</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>telegenceId</m2:name>
                              <m2:value>${telegenceId}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>technicianDispatchIndicator</m2:name>
                              <m2:value>${technicianDispatchIndicator}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>Speed</m2:name>
                              <m2:value>${speed}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shippingIndicator</m2:name>
                              <m2:value>Tech</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>IA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>walledGarden</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProductFamily</m2:name>
                              <m2:value>LightSpeed</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>PortalProvider</m2:name>
                              <m2:value>AT&amp;T Yahoo</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>OMS_QA_COMPONENT_NAME</m2:name>
                              <m2:value>QHSIA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>memberId</m2:name>
                              <m2:value>amy.bruhn</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>materialCode</m2:name>
                              <m2:value>100000290</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>HsiaType</m2:name>
                              <m2:value>Yahoo</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>AMSSDefaultInd</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>amssRefresh</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sbcAffiliate</m2:name>
                              <m2:value>LightSpeed</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>AMSS_LinkInd</m2:name>
                              <m2:value>No_Link</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>NA</m2:value>
                            </m2:attribute>
                            <#if transportType=='FTTB-F' || transportType == 'FTTB-C'>
		   <m2:attribute>
                              <m2:name>IWSS</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
		   <m2:componentList>
                            <m2:component>
                              <m2:assignedProductId>879674564</m2:assignedProductId>
                              <m2:serviceType>WIRING</m2:serviceType>
                              <m2:actionIndicator>I</m2:actionIndicator>
                            </m2:component>
                          </m2:componentList>                 
</#if>
                      <#if transportType=='FTTN' || transportType=='FTTP-GPON'>
                      </m2:attributeList>
                      </#if>
                        </m2:component>
                      </m2:componentList>
                    </m2:component>
                  </m2:componentList>
                </m2:product>
              </m2:productList>
              <m2:extendedDueDateIndicator>N</m2:extendedDueDateIndicator>
              <m2:retainedServicesProcessIndicator>false</m2:retainedServicesProcessIndicator>
              <m2:dslDisconnectTns>1342734237</m2:dslDisconnectTns>
            </m2:orderActionInfo>
          </m2:orderActionInfoList>
          <m2:customerInfoList>
            <m2:customerInfo>
              <m2:accountId>${ban}</m2:accountId>
              <m2:currentCustomerIndicator>true</m2:currentCustomerIndicator>
              <m2:name>${firstName} ${lastName}</m2:name>
              <m2:type>I</m2:type>
              <m2:subType>${subType}</m2:subType>
              <m2:UBIndicator>false</m2:UBIndicator>
              <m2:classOfService>Residential</m2:classOfService>
              <m2:legalEntity>King</m2:legalEntity>
              <m2:creditRiskClass>High</m2:creditRiskClass>
              <m2:timeZoneOffset>${timeZoneOffset}</m2:timeZoneOffset>
              <m2:billCycle>30</m2:billCycle>
              <m2:billRound>2</m2:billRound>
              <m2:customerInfoContactList>
                <m2:customerInfoContact>
                  <m2:contactType>CU</m2:contactType>
                  <m2:title>Mr</m2:title>
                  <m2:firstName>${firstName}</m2:firstName>
                  <m2:lastName>${lastName}</m2:lastName>
                  <m2:phoneNumber>9119119111</m2:phoneNumber>
                  <m2:secondaryPhoneNumber>1191191191</m2:secondaryPhoneNumber>
                  <#if transportType=='FTTB-F' || transportType == 'FTTB-C'>
		    <m2:SellerName>ATT</m2:SellerName>
                  <m2:SellerTn>1081081081</m2:SellerTn>
                  <m2:SellerId>abc123</m2:SellerId>                 
</#if>
                </m2:customerInfoContact>
              </m2:customerInfoContactList>
            </m2:customerInfo>
          </m2:customerInfoList>
        </m2:order>
      </m2:transactionInfo>
    </m2:bbnmsOrder>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>