<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
		  <soap:Header>
    <MessageHeader xmlns="http://lightspeed.bbnms.att.com/header" xmlns:ns2="http://lightspeed.bbnms.att.com/ordering">
      <ch:WSHeader xmlns:soap="http://schemas.xmlsoap.org/soap/envelope" xmlns:ch="http://cio.att.com/commonheader/v3" xmlns:bbnmsOrderHeader="http://lightspeed.bbnms.att.com/header" xmlns:dh="http://aftdiscovery.att.com/header/v1">
        <ch:WSContext>
          <ch:WSNameValue>
            <ch:Name>Application</ch:Name>
            <ch:Value>OMS</ch:Value>
          </ch:WSNameValue>
          <ch:WSNameValue>
            <ch:Name>BusinessUnit</ch:Name>
            <ch:Value>SBCLightSpeed</ch:Value>
          </ch:WSNameValue>
          <ch:WSNameValue>
            <ch:Name>CustomerName</ch:Name>
            <ch:Value>LightSpeed</ch:Value>
          </ch:WSNameValue>
          <ch:WSNameValue>
            <ch:Name>LoggingInformation</ch:Name>
            <ch:Value>COR:MknkAgC6h1WHKQwKs7A|SEQ:0</ch:Value>
          </ch:WSNameValue>
          <ch:WSNameValue>
            <ch:Name>OMS_UserID</ch:Name>
            <ch:Value>js843f</ch:Value>
          </ch:WSNameValue>
          <ch:WSNameValue>
            <ch:Name>OMS_RequestID</ch:Name>
            <ch:Value>MknkAgC6h1WHKQwKs7A</ch:Value>
          </ch:WSNameValue>
          <ch:WSNameValue>
            <ch:Name>OMS_LogicalServer</ch:Name>
            <ch:Value>prdstl2_csr2.12</ch:Value>
          </ch:WSNameValue>
          <ch:WSNameValue>
            <ch:Name>OMS_InterfaceName</ch:Name>
            <ch:Value>SendBroadbandProvisioning</ch:Value>
          </ch:WSNameValue>
        </ch:WSContext>
        <ch:WSCallback>
          <ch:WSCorrelationId>MknkAgC6h1WHKQwKs7A</ch:WSCorrelationId>
        </ch:WSCallback>
        <ch:WSConversationId>MknkAgC6h1WHKQwKs7A</ch:WSConversationId>
        <ch:WSMessageData>
          <ch:RefToMessageId>SendBroadbandProvisioningAck</ch:RefToMessageId>
        </ch:WSMessageData>
        <ch:WSResponseMessageExpiration>86400000</ch:WSResponseMessageExpiration>
        <ch:WSEnterpriseLogging>
          <ch:ApplicationID>m26217</ch:ApplicationID>
          <ch:LoggingKey>MknkAgC6h1WHKQwKs7A</ch:LoggingKey>
        </ch:WSEnterpriseLogging>
      </ch:WSHeader>
      <dh:WSDiscovery xmlns:soap="http://schemas.xmlsoap.org/soap/envelope" xmlns:ch="http://cio.att.com/commonheader/v3" xmlns:bbnmsOrderHeader="http://lightspeed.bbnms.att.com/header" xmlns:dh="http://aftdiscovery.att.com/header/v1">
        <dh:name>http://bbnms.att.com/provisioning/BBNMSLS</dh:name>
        <dh:version>
          <dh:major>1</dh:major>
          <dh:minor>0</dh:minor>
        </dh:version>
        <dh:envContext>Y</dh:envContext>
        <dh:bindingType>fusionBus</dh:bindingType>
      </dh:WSDiscovery>
    </MessageHeader>
  </soap:Header>
  <soap:Body>
    <ns2:bbnmsOrder xmlns="http://lightspeed.bbnms.att.com/header" xmlns:ns2="http://lightspeed.bbnms.att.com/ordering">
      <ns2:transactionInfo xmlns:bbnmsOrder="http://lightspeed.bbnms.att.com/ordering" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <ns2:transactionId>MknkAgC6h1WHKQwKs7A</ns2:transactionId>
        <ns2:taskName>${taskName}</ns2:taskName>
        <ns2:cvoipSdpProvisioningInd>true</ns2:cvoipSdpProvisioningInd>
        <ns2:order>
          <ns2:orderActionInfoList>
            <ns2:orderActionInfo>
              <ns2:orderNumber>${orderNumber}</ns2:orderNumber>
              <ns2:orderActionId>${orderNumber}</ns2:orderActionId>
              <ns2:originalOrderActionId>${origOrderActId}</ns2:originalOrderActionId>
              <ns2:orderActionType>${orderActionType}</ns2:orderActionType>
              <ns2:orderActionSubType>${orderActionSubType}</ns2:orderActionSubType>
              <ns2:orderActionReferenceNumber>${orderNumber}${orderActionReferenceNumber}</ns2:orderActionReferenceNumber>
              <ns2:orderCreationDate>${orderCreationDate}</ns2:orderCreationDate>
              <ns2:assignedProductId>8505678124</ns2:assignedProductId>
              <ns2:creationApplication>OMS</ns2:creationApplication>
              <#if taskName == "BANTreatment" && orderActionType == "SU">
              <ns2:orderActionReasonCode>NP</ns2:orderActionReasonCode>
              <#elseif taskName == "BANTreatment" && orderActionType == "RS">
              <ns2:orderActionReasonCode>OT</ns2:orderActionReasonCode>
              </#if>
              <ns2:salesChannel>TE</ns2:salesChannel>
              <ns2:exhaustHoldDate>2015-06-30T00:00:00</ns2:exhaustHoldDate>
              <ns2:dueDate>${dueDate}</ns2:dueDate>
              <ns2:appointment>
                <ns2:startTime>${apt_start}</ns2:startTime>
                <ns2:endTime>${apt_end}</ns2:endTime>
              </ns2:appointment>
              <ns2:orderActionStatus>DE</ns2:orderActionStatus>
              <ns2:addressInfoList>
                <ns2:addressInfo>
                  <ns2:addressType>LSBilling</ns2:addressType>
                  <ns2:fieldedAddress>
                    <ns2:houseNumber>12</ns2:houseNumber>
                    <ns2:streetName>CAMPBELL</ns2:streetName>
                    <ns2:streetThoroughfare>3</ns2:streetThoroughfare>
                    <ns2:city>COLUMBUS</ns2:city>
                    <ns2:state>OH</ns2:state>
                    <ns2:postalCode>75081</ns2:postalCode>
                    <ns2:cassAddressLines>
                      <ns2:addressLine>JASON RUDOLPH</ns2:addressLine>
                      <ns2:addressLine>315 BYRON RD</ns2:addressLine>
                      <ns2:addressLine>HOWELL MI 48843</ns2:addressLine>
                    </ns2:cassAddressLines>
                    <ns2:addressId>118423380</ns2:addressId>
                  </ns2:fieldedAddress>
                </ns2:addressInfo>
                <ns2:addressInfo>
                  <ns2:addressType>ServiceSAG</ns2:addressType>
                  <ns2:fieldedAddress>
                    <ns2:houseNumber>315</ns2:houseNumber>
                    <ns2:streetName>BYRON</ns2:streetName>
                    <ns2:streetThoroughfare>RD</ns2:streetThoroughfare>
                    <ns2:city>HOWELL</ns2:city>
                    <ns2:state>MI</ns2:state>
                    <ns2:postalCode>48843</ns2:postalCode>
                    <ns2:postalCodePlus4>1405</ns2:postalCodePlus4>
                    <ns2:addressId>118423379</ns2:addressId>
                  </ns2:fieldedAddress>
                </ns2:addressInfo>
                <ns2:addressInfo>
                  <ns2:addressType>ServiceFSP</ns2:addressType>
                  <ns2:primaryNpanxx>123456</ns2:primaryNpanxx>
                  <ns2:clli8>HOWLMIMN</ns2:clli8>
                  <ns2:livingUnitAddressId>F5abdb6387</ns2:livingUnitAddressId>
                  <ns2:rateCenterCode>BARKER</ns2:rateCenterCode>
                  <ns2:dmaCode>623</ns2:dmaCode>
                  <ns2:vhoCode>AUS2TX</ns2:vhoCode>
                  <ns2:tarCode>SAM</ns2:tarCode>
                  <ns2:fieldedAddress>
                    <ns2:houseNumber>12</ns2:houseNumber>
                    <ns2:streetName>CAMPBELL</ns2:streetName>
                    <ns2:streetThoroughfare>3</ns2:streetThoroughfare>
                    <ns2:city>COLUMBUS</ns2:city>
                    <ns2:state>OH</ns2:state>
                    <ns2:postalCode>75081</ns2:postalCode>
                    <ns2:postalCodePlus4/>
                    <ns2:cassAddressLines>
                      <ns2:addressLine>315 BYRON RD</ns2:addressLine>
                      <ns2:addressLine>HOWELL</ns2:addressLine>
                      <ns2:addressLine>MI 48843</ns2:addressLine>
                    </ns2:cassAddressLines>
                    <ns2:addressId>118423379</ns2:addressId>
                  </ns2:fieldedAddress>
                </ns2:addressInfo>
                <ns2:addressInfo>
                  <ns2:addressType>ServiceUSPS</ns2:addressType>
                  <ns2:fieldedAddress>
                    <ns2:houseNumber>315</ns2:houseNumber>
                    <ns2:streetName>BYRON</ns2:streetName>
                    <ns2:streetThoroughfare>RD</ns2:streetThoroughfare>
                    <ns2:city>HOWELL</ns2:city>
                    <ns2:state>MI</ns2:state>
                    <ns2:postalCode>48843</ns2:postalCode>
                    <ns2:cassAddressLines>
                      <ns2:addressLine>315 BYRON RD</ns2:addressLine>
                      <ns2:addressLine>HOWELL</ns2:addressLine>
                      <ns2:addressLine>MI 48843</ns2:addressLine>
                    </ns2:cassAddressLines>
                    <ns2:addressId>118423379</ns2:addressId>
                  </ns2:fieldedAddress>
                </ns2:addressInfo>
                <ns2:addressInfo>
                  <ns2:addressType>MSAG</ns2:addressType>
                  <ns2:fieldedAddress>
                    <ns2:houseNumber>315</ns2:houseNumber>
                    <ns2:streetName>BYRON RD</ns2:streetName>
                    <ns2:city>HOWELL</ns2:city>
                    <ns2:state>MI</ns2:state>
                    <ns2:postalCode>48843</ns2:postalCode>
                    <ns2:addressId>1269164602</ns2:addressId>
                  </ns2:fieldedAddress>
                </ns2:addressInfo>
              </ns2:addressInfoList>
              <ns2:productList>
                <ns2:product>
                  <ns2:name>AT&amp;T WLL DATA</ns2:name>
                  <ns2:componentList>
                    <ns2:component>
                      <ns2:assignedProductId>8505678124</ns2:assignedProductId>
                      <ns2:serviceType>WDM</ns2:serviceType>
					  <#if wdmInd?has_content>
                      <ns2:actionIndicator>${wdmInd}</ns2:actionIndicator>
					  </#if>
                      <ns2:attributeList>
                        <ns2:attribute>
                          <ns2:name>serviceID</ns2:name>
                          <ns2:value>${serviceID}</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>market</ns2:name>
                          <ns2:value>marketBB</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>APID</ns2:name>
                          <ns2:value>8505678124</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>subMarket</ns2:name>
                          <ns2:value>subCC</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>installationType</ns2:name>
                          <ns2:value>TECH</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>technicianDispatchIndicator</ns2:name>
                          <ns2:value>install</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>shippingIndicator</ns2:name>
                          <ns2:value>Tech</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>moveIndicator</ns2:name>
                          <ns2:value>NA</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>transportType</ns2:name>
                          <ns2:value>WLL-LTE</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>SubTransportType</ns2:name>
                          <ns2:value>${subTransportType}</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>isSendToTeLS</ns2:name>
                          <ns2:value>Parent</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>ProdType</ns2:name>
                          <ns2:value>WD</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>offerSalesMode</ns2:name>
                          <ns2:value>Lead</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>completionIndicator</ns2:name>
                          <ns2:value>None</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>disclosureID</ns2:name>
                          <ns2:value>id</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>fulfillmentIndicator</ns2:name>
                          <ns2:value>No</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>orderReasonCode</ns2:name>
                          <ns2:value>code</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>ProductFamily</ns2:name>
                          <ns2:value>prod</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>sapOrderStatus</ns2:name>
                          <ns2:value>Unknown</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>supersedeIndicator</ns2:name>
                          <ns2:value>NA</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>telegenceId</ns2:name>
                          <ns2:value>id</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>VSEndDate</ns2:name>
                          <ns2:value>07/04/2015</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>VSStartDate</ns2:name>
                          <ns2:value>07/04/2015</ns2:value>
                        </ns2:attribute>
						<ns2:attribute>
                          <ns2:name>workOrderId</ns2:name>
                          <ns2:value>${workOrderId}</ns2:value>
                        </ns2:attribute>
                        <ns2:attribute>
                          <ns2:name>previousWorkOrderId</ns2:name>
                          <ns2:value>${prevWorkOrderId}</ns2:value>
                        </ns2:attribute>
                      </ns2:attributeList>
                      <ns2:componentList>
                        <ns2:component>
                          <ns2:assignedProductId>8505712084</ns2:assignedProductId>
                          <ns2:serviceType>WLLD</ns2:serviceType>
						  <#if wlldInd?has_content>
                          <ns2:actionIndicator>${wlldInd}</ns2:actionIndicator>
						  </#if>
                          <ns2:attributeList>
                            <ns2:attribute>
                              <ns2:name>APID</ns2:name>
                              <ns2:value>8505712084</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>dataSpeed</ns2:name>
                              <ns2:value>${dataSpeed}</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>dataBucket</ns2:name>
                              <ns2:value>dummy</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>memberID</ns2:name>
                              <ns2:value>id</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>moveIndicator</ns2:name>
                              <ns2:value>NA</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>techAndShipmentSelection</ns2:name>
                              <ns2:value>TNN</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>isSendToTeLS</ns2:name>
                              <ns2:value>Child</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>action_type</ns2:name>
                              <ns2:value>A</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>ProdType</ns2:name>
                              <ns2:value>WD</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>offerSalesMode</ns2:name>
                              <ns2:value>Lead</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>fulfillmentIndicator</ns2:name>
                              <ns2:value>Yes</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>availableForSelfInstall</ns2:name>
                              <ns2:value>true</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>sapOrderStatus</ns2:name>
                              <ns2:value>Unknown</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>shipmentType</ns2:name>
                              <ns2:value>G</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>actualMaterialCode</ns2:name>
                              <ns2:value>code</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>actualMaterialDescription</ns2:name>
                              <ns2:value>desc</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>criticalFullfillment</ns2:name>
                              <ns2:value>Yes</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>IpQuantity</ns2:name>
                              <ns2:value>2</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>ipAddressType</ns2:name>
                              <ns2:value>true</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>materialCode</ns2:name>
                              <ns2:value>code</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>PortalProvider</ns2:name>
                              <ns2:value>AAA</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>RMA</ns2:name>
                              <ns2:value>N</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>sapOrderNumber</ns2:name>
                              <ns2:value>number</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>shippingDate</ns2:name>
                              <ns2:value>07/04/2015</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>termsAcceptance</ns2:name>
                              <ns2:value>N</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>completionIndicator</ns2:name>
                              <ns2:value>None</ns2:value>
                            </ns2:attribute>
                          </ns2:attributeList>
                        </ns2:component>
                        <ns2:component>
                          <ns2:assignedProductId>8505712108</ns2:assignedProductId>
                          <ns2:serviceType>WSIM</ns2:serviceType>
						  <#if wsimInd?has_content>
                          <ns2:actionIndicator>${wsimInd}</ns2:actionIndicator>
						  </#if>
                          <ns2:attributeList>
                            <ns2:attribute>
                              <ns2:name>APID</ns2:name>
                              <ns2:value>8505712108</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>WSIMTN</ns2:name>
                              <ns2:value>${tnPrefix}${ban}</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>moveIndicator</ns2:name>
                              <ns2:value>NA</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>isSendToTeLS</ns2:name>
                              <ns2:value>None</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>ProdType</ns2:name>
                              <ns2:value>WD</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>offerSalesMode</ns2:name>
                              <ns2:value>Lead</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>fulfillmentIndicator</ns2:name>
                              <ns2:value>Yes</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>ICCID</ns2:name>
                              <ns2:value>ID</ns2:value>
                            </ns2:attribute>
                          </ns2:attributeList>
                        </ns2:component>
                        <ns2:component>
                          <ns2:assignedProductId>8505711796</ns2:assignedProductId>
                          <ns2:serviceType>NAD</ns2:serviceType>
						  <#if wnadInd?has_content>
                          <ns2:actionIndicator>${wnadInd}</ns2:actionIndicator>
						  </#if>
                          <ns2:attributeList>
                            <ns2:attribute>
                              <ns2:name>APID</ns2:name>
                              <ns2:value>8505711796</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>moveIndicator</ns2:name>
                              <ns2:value>NA</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>ProdType</ns2:name>
                              <ns2:value>WD</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>offerSalesMode</ns2:name>
                              <ns2:value>Lead</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>modelNumber</ns2:name>
                              <ns2:value>model</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>materialCode</ns2:name>
                              <ns2:value>Edgemarc 250 IAD</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>manufacturer</ns2:name>
                              <ns2:value>make</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>fulfillmentIndicator</ns2:name>
                              <ns2:value>Yes</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>actualMaterialCode</ns2:name>
                              <ns2:value>code</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>actualMaterialDescription</ns2:name>
                              <ns2:value>desc</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>completionIndicator</ns2:name>
                              <ns2:value>None</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>criticalFullfillment</ns2:name>
                              <ns2:value>No</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>deviceID</ns2:name>
                              <ns2:value>${deviceId}</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>dropShipDate</ns2:name>
                              <ns2:value>07/04/2015</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>RMA</ns2:name>
                              <ns2:value>Unknown</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>sapOrderNumber</ns2:name>
                              <ns2:value>number</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>sapOrderStatus</ns2:name>
                              <ns2:value>Unknown</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>shipmentType</ns2:name>
                              <ns2:value>G</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>shippingDate</ns2:name>
                              <ns2:value>07/04/2015</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>isSendToTeLS</ns2:name>
                              <ns2:value>Child</ns2:value>
                            </ns2:attribute>
                          </ns2:attributeList>
                        </ns2:component>
                        <ns2:component>
                          <ns2:assignedProductId>8505712012</ns2:assignedProductId>
                          <ns2:serviceType>OWA</ns2:serviceType>
						  <#if owaInd?has_content>
                          <ns2:actionIndicator>${owaInd}</ns2:actionIndicator>
						  </#if>
                          <ns2:attributeList>
                            <ns2:attribute>
                              <ns2:name>APID</ns2:name>
                              <ns2:value>8505712012</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>versionID</ns2:name>
                              <ns2:value>0</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>moveIndicator</ns2:name>
                              <ns2:value>NA</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>isSendToTeLS</ns2:name>
                              <ns2:value>Child</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>action_type</ns2:name>
                              <ns2:value>A</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>ProdType</ns2:name>
                              <ns2:value>WRG</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>offerSalesMode</ns2:name>
                              <ns2:value>Lead</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>CellRank1</ns2:name>
                              <ns2:value>1</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>cellSite1</ns2:name>
                              <ns2:value>1</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>latitude1</ns2:name>
                              <ns2:value>2</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>longitude1</ns2:name>
                              <ns2:value>3</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>CellRank2</ns2:name>
                              <ns2:value>2</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>cellSite2</ns2:name>
                              <ns2:value>2</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>latitude2</ns2:name>
                              <ns2:value>late</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>longitude2</ns2:name>
                              <ns2:value>long</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>CellRank3</ns2:name>
                              <ns2:value>3</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>cellSite3</ns2:name>
                              <ns2:value>3</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>latitude3</ns2:name>
                              <ns2:value>lat</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>longitude3</ns2:name>
                              <ns2:value>long</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>manufacturer</ns2:name>
                              <ns2:value>make</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>modelNumber</ns2:name>
                              <ns2:value>model</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>materialCode</ns2:name>
                              <ns2:value>code</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>fulfillmentIndicator</ns2:name>
                              <ns2:value>yes</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>actualMaterialCode</ns2:name>
                              <ns2:value>code</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>actualMaterialDescription</ns2:name>
                              <ns2:value>desc</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>availableForSelfInstall</ns2:name>
                              <ns2:value>true</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>completionIndicator</ns2:name>
                              <ns2:value>None</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>criticalFullfillment</ns2:name>
                              <ns2:value>No</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>deviceID</ns2:name>
                              <ns2:value>Id</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>dropShipDate</ns2:name>
                              <ns2:value>07/04/2015</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>RMA</ns2:name>
                              <ns2:value>N</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>sapOrderNumber</ns2:name>
                              <ns2:value>Number</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>sapOrderStatus</ns2:name>
                              <ns2:value>Unknown</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>shipmentType</ns2:name>
                              <ns2:value>G</ns2:value>
                            </ns2:attribute>
                            <ns2:attribute>
                              <ns2:name>shippingDate</ns2:name>
                              <ns2:value>07/04/2015</ns2:value>
                            </ns2:attribute>
                          </ns2:attributeList>
                        </ns2:component>
                      </ns2:componentList>
                    </ns2:component>
                  </ns2:componentList>
                </ns2:product>
              </ns2:productList>
              <ns2:nonProductCatalogDataList>
                <ns2:nonProductCatalogData>
                  <ns2:name>departmentName</ns2:name>
                  <ns2:value>MW Cons U-verse B.O</ns2:value>
                </ns2:nonProductCatalogData>
                <ns2:nonProductCatalogData>
                  <ns2:name>departmentPhone</ns2:name>
                  <ns2:value>8885444805</ns2:value>
                </ns2:nonProductCatalogData>
              </ns2:nonProductCatalogDataList>
			  <#if rpiWllDataOrderNumber?? || rpiWllvOrdNumber?? || rpiTdarOrderNum?? || rpiUverseOrderNum??>
			  <ns2:relatedProductInfoList>
			  <#if rpiWllDataOrderNumber??>
                <ns2:relatedProductInfo>
                  <ns2:orderNumber>${rpiWllDataOrderNumber}</ns2:orderNumber>
                  <ns2:originalOrderActionId>${rpiWllDataOrigOrderNumber}</ns2:originalOrderActionId>
                  <ns2:orderActionType>${rpiWllDataOrdActionType}</ns2:orderActionType>
                  <ns2:orderActionSubType>${rpiWllDataOrdActSubType}</ns2:orderActionSubType>
                  <ns2:orderActionReferenceNumber>${rpiWllDataOrigOrderNumber}${rpiWllDataOrdActRef}</ns2:orderActionReferenceNumber>
                  <ns2:appointment>
                    <ns2:startTime>2016-12-17T09:30:47.0Z</ns2:startTime>
                    <ns2:endTime>2016-12-18T09:30:47.0Z</ns2:endTime>
                  </ns2:appointment>
                  <ns2:orderActionStatus>${rpiWllDataOrdActStatus}</ns2:orderActionStatus>
                  <ns2:dueDate>${rpiWllDataDueDate}</ns2:dueDate>
                  <ns2:workOrderID>${workOrderId}</ns2:workOrderID>
                  <ns2:previousWorkOrderID>${prevWorkOrderId}</ns2:previousWorkOrderID>
                  <ns2:serviceType>WDM</ns2:serviceType>
                </ns2:relatedProductInfo>
				</#if>
				<#if rpiWllvOrdNumber??>
				<ns2:relatedProductInfo>
					<ns2:orderNumber>${rpiWllvOrdNumber}</ns2:orderNumber>
					<ns2:originalOrderActionId>${rpiWllvOrigOrdNum}</ns2:originalOrderActionId>
					<ns2:orderActionType>${rpiWllvOrdActionType}</ns2:orderActionType>
					<ns2:orderActionSubType>${rpiWllvOrdActSubType}</ns2:orderActionSubType>
					<ns2:orderActionReferenceNumber>${rpiWllvOrigOrdNum}${rpiWllvOrdRef}</ns2:orderActionReferenceNumber>
					<ns2:appointment>
					<ns2:startTime>2016-12-17T09:30:47.0Z</ns2:startTime>
					<ns2:endTime>2016-12-18T09:30:47.0Z</ns2:endTime>
					</ns2:appointment>
					<ns2:orderActionStatus>${rpiWllvOrdActStatus}</ns2:orderActionStatus>
					<ns2:dueDate>${rpiWllvDueDate}</ns2:dueDate>
					<ns2:workOrderID>${rpiWllvWorkOrdId}</ns2:workOrderID>
					<ns2:previousWorkOrderID>${rpiWllvPrvWorkOrdId}</ns2:previousWorkOrderID>
					<ns2:serviceType>WVM</ns2:serviceType>
				</ns2:relatedProductInfo>
				</#if>
				<#if rpiTdarOrderNum??>
				<ns2:relatedProductInfo>
					<ns2:orderNumber>${rpiTdarOrderNum}</ns2:orderNumber>
					<ns2:originalOrderActionId>${rpiTdarOrigOrderNum}</ns2:originalOrderActionId>
					<ns2:orderActionType>${rpiTdarOrderActType}</ns2:orderActionType>
					<ns2:orderActionSubType>${rpiTdarOrderActSubType}</ns2:orderActionSubType>
					<ns2:orderActionReferenceNumber>${rpiTdarOrigOrderNum}${rpiTdarOrderRef}</ns2:orderActionReferenceNumber>
					<ns2:appointment>
					<ns2:startTime>2016-12-17T09:30:47.0Z</ns2:startTime>
					<ns2:endTime>2016-12-18T09:30:47.0Z</ns2:endTime>
					</ns2:appointment>
					<ns2:orderActionStatus>${rpiTdarOrdActStatus}</ns2:orderActionStatus>
					<ns2:dueDate>${rpiTdarDueDate}</ns2:dueDate>
					<ns2:workOrderID>${rpiTdarWorkOrderId}</ns2:workOrderID>
					<ns2:previousWorkOrderID>${rpiTdarPrvWorkOrderId}</ns2:previousWorkOrderID>
					<ns2:serviceType>DTVM</ns2:serviceType>
				</ns2:relatedProductInfo>
				</#if>
				<#if rpiUverseOrderNum??>
				<ns2:relatedProductInfo>
					<ns2:orderNumber>${rpiUverseOrderNum}</ns2:orderNumber>
					<ns2:originalOrderActionId>${rpiUverseOrigOrderNum}</ns2:originalOrderActionId>
					<ns2:orderActionType>${rpiUverseOrderActType}</ns2:orderActionType>
					<ns2:orderActionSubType>${rpiUverseOrderActSubType}</ns2:orderActionSubType>
					<ns2:orderActionReferenceNumber>${rpiUverseOrderNum}${rpiUverseOrderRef}</ns2:orderActionReferenceNumber>
					<ns2:appointment>
					<ns2:startTime>2016-12-17T09:30:47.0Z</ns2:startTime>
					<ns2:endTime>2016-12-18T09:30:47.0Z</ns2:endTime>
					</ns2:appointment>
					<ns2:orderActionStatus>${rpiUverseOrdActStatus}</ns2:orderActionStatus>
					<ns2:dueDate>${rpiUverseDueDate}</ns2:dueDate>
					<ns2:workOrderID>${rpiUverseWorkOrderId}</ns2:workOrderID>
					<ns2:previousWorkOrderID>${rpiUversePrvWorkOrderId}</ns2:previousWorkOrderID>
					<ns2:serviceType>UMC</ns2:serviceType>
				</ns2:relatedProductInfo>
				</#if>
              </ns2:relatedProductInfoList>
			  </#if>
            </ns2:orderActionInfo>
          </ns2:orderActionInfoList>
          <ns2:customerInfoList>
            <ns2:customerInfo>
              <ns2:accountId>${ban}</ns2:accountId>
              <ns2:currentCustomerIndicator>true</ns2:currentCustomerIndicator>
              <ns2:name>Charlie</ns2:name>
              <ns2:type>I</ns2:type>
              <ns2:subType>R</ns2:subType>
              <ns2:UBIndicator>false</ns2:UBIndicator>
              <ns2:classOfService>Residential</ns2:classOfService>
              <ns2:legalEntity>AM00</ns2:legalEntity>
              <ns2:creditRiskClass>Low</ns2:creditRiskClass>
              <ns2:timeZoneOffset>-5</ns2:timeZoneOffset>
              <ns2:billCycle>26</ns2:billCycle>
              <ns2:billRound>25</ns2:billRound>
              <ns2:customerInfoContactList>
                <ns2:customerInfoContact>
                  <ns2:contactType>CU</ns2:contactType>
                  <ns2:firstName>WILL</ns2:firstName>
                  <ns2:lastName>SMITH</ns2:lastName>
                  <ns2:phoneNumber>4045578890</ns2:phoneNumber>
                  <ns2:secondaryPhoneNumber>4046451234</ns2:secondaryPhoneNumber>
                </ns2:customerInfoContact>
              </ns2:customerInfoContactList>
            </ns2:customerInfo>
          </ns2:customerInfoList>
        </ns2:order>
      </ns2:transactionInfo>
    </ns2:bbnmsOrder>
  </soap:Body>
</soap:Envelope>