<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:m1="http://lightspeed.bbnms.att.com/header" xmlns:m2="http://lightspeed.bbnms.att.com/ordering" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SOAP-ENV:Header>
    <m1:MessageHeader xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:bbnmsOrderHeader="http://lightspeed.bbnms.att.com/header">
      <ns2:WSHeader xmlns:ns2="http://cio.att.com/commonheader/v3">
        <ns2:WSContext>
          <ns2:SourceIPAddress>10.160.249.210</ns2:SourceIPAddress>
        </ns2:WSContext>
        <ns2:WSMessageData>
          <ns2:Timestamp>2008-02-19T10:09:25.0440</ns2:Timestamp>
        </ns2:WSMessageData>
        <ns2:WSEnterpriseLogging>
          <ns2:LoggingKey>tE3AAHzMnFWHvNHWJoo</ns2:LoggingKey>
        </ns2:WSEnterpriseLogging>
      </ns2:WSHeader>
      <ns1:WSDiscovery xmlns:ns1="http://aftdiscovery.att.com/header/v1">
        <ns1:name>MQSSL_ESB_J2EEEJB_ON_AIX</ns1:name>
        <ns1:version>
          <ns1:major>3</ns1:major>
          <ns1:minor>0</ns1:minor>
        </ns1:version>
        <ns1:envContext>Y</ns1:envContext>
        <ns1:bindingType>fusionBus</ns1:bindingType>
      </ns1:WSDiscovery>
    </m1:MessageHeader>
  </SOAP-ENV:Header>
  <SOAP-ENV:Body>
    <m2:bbnmsOrder>
      <m2:transactionInfo xmlns:bbnmsOrder="http://lightspeed.bbnms.att.com/ordering">
        <m2:transactionId>MknkAgC6h1WHKQwKs7A</m2:transactionId>
        <m2:taskName>${taskName}</m2:taskName>
        <m2:cvoipSdpProvisioningInd>true</m2:cvoipSdpProvisioningInd>
        <m2:order>
          <m2:orderActionInfoList>
            <m2:orderActionInfo>
              <m2:orderNumber>${orderNumber}</m2:orderNumber>
              <m2:orderActionId>${orderNumber}</m2:orderActionId>
              <m2:originalOrderActionId>${orderNumberPvData}</m2:originalOrderActionId>
              <m2:orderActionType>PV</m2:orderActionType>
              <m2:orderActionSubType>${orderActionSubTypePv}</m2:orderActionSubType>
              <m2:orderActionReferenceNumber>${orderNumberPvData}${orderActionReferenceNumberPv}</m2:orderActionReferenceNumber>
              <m2:orderCreationDate>${orderCreationDatePv}</m2:orderCreationDate>
              <m2:assignedProductId>8505678124</m2:assignedProductId>
              <m2:creationApplication>OMS</m2:creationApplication>
              <m2:salesChannel>TE</m2:salesChannel>
              <m2:exhaustHoldDate>2015-06-30T00:00:00</m2:exhaustHoldDate>
              <m2:dueDate>${dueDatePv}</m2:dueDate>
              <m2:appointment>
                <m2:startTime>${apt_start}</m2:startTime>
                <m2:endTime>${apt_end}</m2:endTime>
              </m2:appointment>
              <m2:orderActionStatus>DE</m2:orderActionStatus>
              <m2:addressInfoList>
                <m2:addressInfo>
                  <m2:addressType>LSBilling</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>315</m2:houseNumber>
                    <m2:streetName>BYRON</m2:streetName>
                    <m2:streetThoroughfare>RD</m2:streetThoroughfare>
                    <m2:city>HOWELL</m2:city>
                    <m2:state>MI</m2:state>
                    <m2:postalCode>48843</m2:postalCode>
                    <m2:cassAddressLines>
                      <m2:addressLine>JASON RUDOLPH</m2:addressLine>
                      <m2:addressLine>315 BYRON RD</m2:addressLine>
                      <m2:addressLine>HOWELL MI 48843</m2:addressLine>
                    </m2:cassAddressLines>
                    <m2:addressId>118423380</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>ServiceSAG</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>315</m2:houseNumber>
                    <m2:streetName>BYRON</m2:streetName>
                    <m2:streetThoroughfare>RD</m2:streetThoroughfare>
                    <m2:city>HOWELL</m2:city>
                    <m2:state>MI</m2:state>
                    <m2:postalCode>48843</m2:postalCode>
                    <m2:postalCodePlus4>1405</m2:postalCodePlus4>
                    <m2:addressId>118423379</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>ServiceFSP</m2:addressType>
                  <m2:primaryNpanxx>123456</m2:primaryNpanxx>
                  <m2:clli8>HOWLMIMN</m2:clli8>
                  <m2:livingUnitAddressId>F5abdb6387</m2:livingUnitAddressId>
                  <m2:rateCenterCode>BARKER</m2:rateCenterCode>
                  <m2:dmaCode>623</m2:dmaCode>
                  <m2:vhoCode>AUS2TX</m2:vhoCode>
                  <m2:tarCode>SAM</m2:tarCode>
                  <m2:fieldedAddress>
                    <m2:houseNumber>16</m2:houseNumber>
                    <m2:streetName>CAMPBELL</m2:streetName>
                    <m2:streetThoroughfare>3</m2:streetThoroughfare>
                    <m2:city>COLUMBUS</m2:city>
                    <m2:state>OH</m2:state>
                    <m2:postalCode>75081</m2:postalCode>
                    <m2:postalCodePlus4>1405</m2:postalCodePlus4>
                    <m2:cassAddressLines>
                      <m2:addressLine>16CAMPBELL3</m2:addressLine>
                      <m2:addressLine>COLUMBUS</m2:addressLine>
                      <m2:addressLine>OH75081</m2:addressLine>
                    </m2:cassAddressLines>
                    <m2:addressId>${addressIdPvData}</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>ServiceUSPS</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>315</m2:houseNumber>
                    <m2:streetName>BYRON</m2:streetName>
                    <m2:streetThoroughfare>RD</m2:streetThoroughfare>
                    <m2:city>HOWELL</m2:city>
                    <m2:state>MI</m2:state>
                    <m2:postalCode>48843</m2:postalCode>
                    <m2:cassAddressLines>
                      <m2:addressLine>315   BYRON RD</m2:addressLine>
                      <m2:addressLine>HOWELL</m2:addressLine>
                      <m2:addressLine>MI 48843</m2:addressLine>
                    </m2:cassAddressLines>
                    <m2:addressId>118423379</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>MSAG</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>315</m2:houseNumber>
                    <m2:streetName>BYRON RD</m2:streetName>
                    <m2:city>HOWELL</m2:city>
                    <m2:state>MI</m2:state>
                    <m2:postalCode>48843</m2:postalCode>
                    <m2:addressId>1269164602</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
              </m2:addressInfoList>
              <m2:productList>
                <m2:product>
                  <m2:name>AT&amp;T WLL DATA</m2:name>
                  <m2:componentList>
                    <m2:component>
                      <m2:assignedProductId>8505678124</m2:assignedProductId>
                      <m2:serviceType>WDM</m2:serviceType>
                      <m2:actionIndicator>${wdmIndPv}</m2:actionIndicator>
                      <m2:attributeList>
                        <m2:attribute>
                          <m2:name>serviceID</m2:name>
                          <m2:value>${serviceIdPv}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>market</m2:name>
                          <m2:value>marketBB</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>APID</m2:name>
                          <m2:value>8505678124</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>subMarket</m2:name>
                          <m2:value>subCC</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>transportType</m2:name>
                          <m2:value>WLL-LTE</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>installationType</m2:name>
                          <m2:value>TECH</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>SubTransportType</m2:name>
                          <m2:value>${subTransportType}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>technicianDispatchIndicator</m2:name>
                          <m2:value>install</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>shippingIndicator</m2:name>
                          <m2:value>Tech</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>moveIndicator</m2:name>
                          <m2:value>N</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>isSendToTeLS</m2:name>
                          <m2:value>Parent</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>ProdType</m2:name>
                          <m2:value>WD</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>offerSalesMode</m2:name>
                          <m2:value>Lead</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>completionIndicator</m2:name>
                          <m2:value>None</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>disclosureID</m2:name>
                          <m2:value>id</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>fulfillmentIndicator</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>orderReasonCode</m2:name>
                          <m2:value>code</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>ProductFamily</m2:name>
                          <m2:value>prod</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>sapOrderStatus</m2:name>
                          <m2:value>Unknown</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>supersedeIndicator</m2:name>
                          <m2:value>NA</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>telegenceId</m2:name>
                          <m2:value>id</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>VSEndDate</m2:name>
                          <m2:value>07/04/2015</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>VSStartDate</m2:name>
                          <m2:value>07/04/2015</m2:value>
                        </m2:attribute>
                      </m2:attributeList>
                      <m2:componentList>
                        <m2:component>
                          <m2:assignedProductId>8505712084</m2:assignedProductId>
                          <m2:serviceType>WLLD</m2:serviceType>
                          <m2:actionIndicator>${wlldIndPv}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>8505712084</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>dataSpeed</m2:name>
                              <m2:value>fast</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>dataBucket</m2:name>
                              <m2:value>dummy</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>memberID</m2:name>
                              <m2:value>id</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>techAndShipmentSelection</m2:name>
                              <m2:value>TNN</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>Child</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>action_type</m2:name>
                              <m2:value>A</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>WD</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>availableForSelfInstall</m2:name>
                              <m2:value>NA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderStatus</m2:name>
                              <m2:value>Unknown</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shipmentType</m2:name>
                              <m2:value>G</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialDescription</m2:name>
                              <m2:value>desc</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>criticalFullfillment</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>IpQuantity</m2:name>
                              <m2:value>2</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ipAddressType</m2:name>
                              <m2:value>true</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>materialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>PortalProvider</m2:name>
                              <m2:value>AAA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>RMA</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderNumber</m2:name>
                              <m2:value>number</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shippingDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>termsAcceptance</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>completionIndicator</m2:name>
                              <m2:value>None</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                        </m2:component>
                        <m2:component>
                          <m2:assignedProductId>8505712108</m2:assignedProductId>
                          <m2:serviceType>WSIM</m2:serviceType>
                          <m2:actionIndicator>${wsimIndPv}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>8505712108</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>WSIMTN</m2:name>
                              <m2:value>${tnPrefix}${ban}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>None</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>WD</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ICCID</m2:name>
                              <m2:value>ID</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                        </m2:component>
                        <m2:component>
                          <m2:assignedProductId>8505711796</m2:assignedProductId>
                          <m2:serviceType>NAD</m2:serviceType>
                          <m2:actionIndicator>${wnadIndPv}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>8505711796</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>WD</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>modelNumber</m2:name>
                              <m2:value>model</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>materialCode</m2:name>
                              <m2:value>Edgemarc 250 IAD</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>manufacturer</m2:name>
                              <m2:value>make</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialDescription</m2:name>
                              <m2:value>desc</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>completionIndicator</m2:name>
                              <m2:value>None</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>criticalFullfillment</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>deviceID</m2:name>
                              <m2:value>${deviceIdPv}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>dropShipDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>RMA</m2:name>
                              <m2:value>Unknown</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderNumber</m2:name>
                              <m2:value>number</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderStatus</m2:name>
                              <m2:value>Unknown</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shipmentType</m2:name>
                              <m2:value>G</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shippingDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>Child</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                        </m2:component>
                        <m2:component>
                          <m2:assignedProductId>8505712012</m2:assignedProductId>
                          <m2:serviceType>OWA</m2:serviceType>
                          <m2:actionIndicator>${owaIndPv}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>8505712012</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>versionID</m2:name>
                              <m2:value>0</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>Child</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>action_type</m2:name>
                              <m2:value>A</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>WRG</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>CellRank1</m2:name>
                              <m2:value>1</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>cellSite1</m2:name>
                              <m2:value>1</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>latitude1</m2:name>
                              <m2:value>lat</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>longitude1</m2:name>
                              <m2:value>long</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>CellRank2</m2:name>
                              <m2:value>2</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>cellSite2</m2:name>
                              <m2:value>2</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>latitude2</m2:name>
                              <m2:value>late</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>longitude2</m2:name>
                              <m2:value>long</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>CellRank3</m2:name>
                              <m2:value>3</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>cellSite3</m2:name>
                              <m2:value>3</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>latitude3</m2:name>
                              <m2:value>lat</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>longitude3</m2:name>
                              <m2:value>long</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>manufacturer</m2:name>
                              <m2:value>make</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>modelNumber</m2:name>
                              <m2:value>model</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>materialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialDescription</m2:name>
                              <m2:value>desc</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>availableForSelfInstall</m2:name>
                              <m2:value>true</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>completionIndicator</m2:name>
                              <m2:value>None</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>criticalFullfillment</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>deviceID</m2:name>
                              <m2:value>Id</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>dropShipDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>RMA</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderNumber</m2:name>
                              <m2:value>Number</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderStatus</m2:name>
                              <m2:value>Unknown</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shipmentType</m2:name>
                              <m2:value>G</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shippingDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                        </m2:component>
                      </m2:componentList>
                    </m2:component>
                  </m2:componentList>
                </m2:product>
              </m2:productList>
              <m2:nonProductCatalogDataList>
                <m2:nonProductCatalogData>
                  <m2:name>departmentName</m2:name>
                  <m2:value>MW Cons U-verse B.O</m2:value>
                </m2:nonProductCatalogData>
                <m2:nonProductCatalogData>
                  <m2:name>departmentPhone</m2:name>
                  <m2:value>8885444805</m2:value>
                </m2:nonProductCatalogData>
              </m2:nonProductCatalogDataList>
            </m2:orderActionInfo>
            <m2:orderActionInfo>
              <m2:orderNumber>${orderNumber}</m2:orderNumber>
              <m2:orderActionId>${orderNumber}</m2:orderActionId>
              <m2:originalOrderActionId>${orderNumberCmData}</m2:originalOrderActionId>
              <m2:orderActionType>CM</m2:orderActionType>
              <m2:orderActionSubType>${orderActionSubTypeCm}</m2:orderActionSubType>
              <m2:orderActionReferenceNumber>${orderNumberCmData}${orderActionReferenceNumberCm}</m2:orderActionReferenceNumber>
              <m2:orderCreationDate>${orderCreationDateCm}</m2:orderCreationDate>
              <m2:assignedProductId>8505678124</m2:assignedProductId>
              <m2:creationApplication>OMS</m2:creationApplication>
              <m2:salesChannel>TE</m2:salesChannel>
              <m2:exhaustHoldDate>2015-06-30T00:00:00</m2:exhaustHoldDate>
              <m2:dueDate>${dueDateCm}</m2:dueDate>
              <m2:appointment>
                <m2:startTime>${apt_start}</m2:startTime>
                <m2:endTime>${apt_end}</m2:endTime>
              </m2:appointment>
              <m2:orderActionStatus>DE</m2:orderActionStatus>
              <m2:addressInfoList>
                <m2:addressInfo>
                  <m2:addressType>LSBilling</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>315</m2:houseNumber>
                    <m2:streetName>BYRON</m2:streetName>
                    <m2:streetThoroughfare>RD</m2:streetThoroughfare>
                    <m2:city>HOWELL</m2:city>
                    <m2:state>MI</m2:state>
                    <m2:postalCode>48843</m2:postalCode>
                    <m2:cassAddressLines>
                      <m2:addressLine>JASON RUDOLPH</m2:addressLine>
                      <m2:addressLine>315 BYRON RD</m2:addressLine>
                      <m2:addressLine>HOWELL MI 48843</m2:addressLine>
                    </m2:cassAddressLines>
                    <m2:addressId>118423380</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>ServiceSAG</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>315</m2:houseNumber>
                    <m2:streetName>BYRON</m2:streetName>
                    <m2:streetThoroughfare>RD</m2:streetThoroughfare>
                    <m2:city>HOWELL</m2:city>
                    <m2:state>MI</m2:state>
                    <m2:postalCode>48843</m2:postalCode>
                    <m2:postalCodePlus4>1405</m2:postalCodePlus4>
                    <m2:addressId>118423379</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>ServiceFSP</m2:addressType>
                  <m2:primaryNpanxx>123456</m2:primaryNpanxx>
                  <m2:clli8>HOWLMIMN</m2:clli8>
                  <m2:livingUnitAddressId>G6abdb6387</m2:livingUnitAddressId>
                  <m2:rateCenterCode>BARKER</m2:rateCenterCode>
                  <m2:dmaCode>623</m2:dmaCode>
                  <m2:vhoCode>AUS2TX</m2:vhoCode>
                  <m2:tarCode>SAM</m2:tarCode>
                  <m2:fieldedAddress>
                    <m2:houseNumber>12</m2:houseNumber>
                    <m2:streetName>CAMPBELL</m2:streetName>
                    <m2:streetThoroughfare>3</m2:streetThoroughfare>
                    <m2:city>COLUMBUS</m2:city>
                    <m2:state>OH</m2:state>
                    <m2:postalCode>75081</m2:postalCode>
                    <m2:postalCodePlus4>1405</m2:postalCodePlus4>
                    <m2:cassAddressLines>
                      <m2:addressLine>12CAMPBELL3</m2:addressLine>
                      <m2:addressLine>COLUMBUS</m2:addressLine>
                      <m2:addressLine>OH75081</m2:addressLine>
                    </m2:cassAddressLines>
                    <m2:addressId>${addressIdCmData}</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>ServiceUSPS</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>315</m2:houseNumber>
                    <m2:streetName>BYRON</m2:streetName>
                    <m2:streetThoroughfare>RD</m2:streetThoroughfare>
                    <m2:city>HOWELL</m2:city>
                    <m2:state>MI</m2:state>
                    <m2:postalCode>48843</m2:postalCode>
                    <m2:cassAddressLines>
                      <m2:addressLine>315   BYRON RD</m2:addressLine>
                      <m2:addressLine>HOWELL</m2:addressLine>
                      <m2:addressLine>MI 48843</m2:addressLine>
                    </m2:cassAddressLines>
                    <m2:addressId>118423379</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
                <m2:addressInfo>
                  <m2:addressType>MSAG</m2:addressType>
                  <m2:fieldedAddress>
                    <m2:houseNumber>315</m2:houseNumber>
                    <m2:streetName>BYRON RD</m2:streetName>
                    <m2:city>HOWELL</m2:city>
                    <m2:state>MI</m2:state>
                    <m2:postalCode>48843</m2:postalCode>
                    <m2:addressId>1269164602</m2:addressId>
                  </m2:fieldedAddress>
                </m2:addressInfo>
              </m2:addressInfoList>
              <m2:productList>
                <m2:product>
                  <m2:name>AT&amp;T WLL DATA</m2:name>
                  <m2:componentList>
                    <m2:component>
                      <m2:assignedProductId>8505678124</m2:assignedProductId>
                      <m2:serviceType>WDM</m2:serviceType>
                      <m2:actionIndicator>${wdmIndCm}</m2:actionIndicator>
                      <m2:attributeList>
                        <m2:attribute>
                          <m2:name>serviceID</m2:name>
                          <m2:value>${serviceIdCm}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>market</m2:name>
                          <m2:value>marketBB</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>APID</m2:name>
                          <m2:value>8505678124</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>subMarket</m2:name>
                          <m2:value>subCC</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>transportType</m2:name>
                          <m2:value>WLL-LTE</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>installationType</m2:name>
                          <m2:value>TECH</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>SubTransportType</m2:name>
                          <m2:value>${subTransportTypeCm}</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>technicianDispatchIndicator</m2:name>
                          <m2:value>install</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>shippingIndicator</m2:name>
                          <m2:value>Tech</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>moveIndicator</m2:name>
                          <m2:value>N</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>isSendToTeLS</m2:name>
                          <m2:value>Parent</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>ProdType</m2:name>
                          <m2:value>WD</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>offerSalesMode</m2:name>
                          <m2:value>Lead</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>completionIndicator</m2:name>
                          <m2:value>None</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>disclosureID</m2:name>
                          <m2:value>id</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>fulfillmentIndicator</m2:name>
                          <m2:value>No</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>orderReasonCode</m2:name>
                          <m2:value>code</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>ProductFamily</m2:name>
                          <m2:value>prod</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>sapOrderStatus</m2:name>
                          <m2:value>Unknown</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>supersedeIndicator</m2:name>
                          <m2:value>NA</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>telegenceId</m2:name>
                          <m2:value>id</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>VSEndDate</m2:name>
                          <m2:value>07/04/2015</m2:value>
                        </m2:attribute>
                        <m2:attribute>
                          <m2:name>VSStartDate</m2:name>
                          <m2:value>07/04/2015</m2:value>
                        </m2:attribute>
                      </m2:attributeList>
                      <m2:componentList>
                        <m2:component>
                          <m2:assignedProductId>8505712084</m2:assignedProductId>
                          <m2:serviceType>WLLD</m2:serviceType>
                          <m2:actionIndicator>${wlldIndCm}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>8505712084</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>dataSpeed</m2:name>
                              <m2:value>fast</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>dataBucket</m2:name>
                              <m2:value>10 gig</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>memberID</m2:name>
                              <m2:value>id</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>techAndShipmentSelection</m2:name>
                              <m2:value>TNN</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>Child</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>action_type</m2:name>
                              <m2:value>A</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>WD</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>availableForSelfInstall</m2:name>
                              <m2:value>true</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderStatus</m2:name>
                              <m2:value>Unknown</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shipmentType</m2:name>
                              <m2:value>G</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialDescription</m2:name>
                              <m2:value>desc</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>criticalFullfillment</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>IpQuantity</m2:name>
                              <m2:value>2</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ipAddressType</m2:name>
                              <m2:value>true</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>materialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>PortalProvider</m2:name>
                              <m2:value>AAA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>RMA</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderNumber</m2:name>
                              <m2:value>number</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shippingDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>termsAcceptance</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>completionIndicator</m2:name>
                              <m2:value>None</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                        </m2:component>
                        <m2:component>
                          <m2:assignedProductId>8505712108</m2:assignedProductId>
                          <m2:serviceType>WSIM</m2:serviceType>
                          <m2:actionIndicator>${wsimIndCm}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>8505712108</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>WSIMTN</m2:name>
                              <m2:value>${tnPrefix}${ban}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>None</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>WD</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ICCID</m2:name>
                              <m2:value>ID</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                        </m2:component>
                        <m2:component>
                          <m2:assignedProductId>8505711796</m2:assignedProductId>
                          <m2:serviceType>NAD</m2:serviceType>
                          <m2:actionIndicator>${wnadIndCm}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>8505711796</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>WD</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>modelNumber</m2:name>
                              <m2:value>model</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>materialCode</m2:name>
                              <m2:value>Edgemarc 250 IAD</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>manufacturer</m2:name>
                              <m2:value>make</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>Yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialDescription</m2:name>
                              <m2:value>desc</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>completionIndicator</m2:name>
                              <m2:value>None</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>criticalFullfillment</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>deviceID</m2:name>
                              <m2:value>${deviceIdCm}</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>dropShipDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>RMA</m2:name>
                              <m2:value>Unknown</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderNumber</m2:name>
                              <m2:value>number</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderStatus</m2:name>
                              <m2:value>Unknown</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shipmentType</m2:name>
                              <m2:value>G</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shippingDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>Child</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                        </m2:component>
                        <m2:component>
                          <m2:assignedProductId>8505712012</m2:assignedProductId>
                          <m2:serviceType>OWA</m2:serviceType>
                          <m2:actionIndicator>${owaIndCm}</m2:actionIndicator>
                          <m2:attributeList>
                            <m2:attribute>
                              <m2:name>APID</m2:name>
                              <m2:value>8505712012</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>versionID</m2:name>
                              <m2:value>0</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>moveIndicator</m2:name>
                              <m2:value>Y</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>isSendToTeLS</m2:name>
                              <m2:value>Child</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>action_type</m2:name>
                              <m2:value>A</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>ProdType</m2:name>
                              <m2:value>WRG</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>offerSalesMode</m2:name>
                              <m2:value>Lead</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>CellRank1</m2:name>
                              <m2:value>1</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>cellSite1</m2:name>
                              <m2:value>ASDF</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>latitude1</m2:name>
                              <m2:value>lat</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>longitude1</m2:name>
                              <m2:value>long</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>CellRank2</m2:name>
                              <m2:value>CellRank2</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>cellSite2</m2:name>
                              <m2:value>site</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>latitude2</m2:name>
                              <m2:value>late</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>longitude2</m2:name>
                              <m2:value>long</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>CellRank3</m2:name>
                              <m2:value>CellRank3</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>cellSite3</m2:name>
                              <m2:value>site</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>latitude3</m2:name>
                              <m2:value>lat</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>longitude3</m2:name>
                              <m2:value>long</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>manufacturer</m2:name>
                              <m2:value>make</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>modelNumber</m2:name>
                              <m2:value>model</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>materialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>fulfillmentIndicator</m2:name>
                              <m2:value>yes</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialCode</m2:name>
                              <m2:value>code</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>actualMaterialDescription</m2:name>
                              <m2:value>desc</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>availableForSelfInstall</m2:name>
                              <m2:value>NA</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>completionIndicator</m2:name>
                              <m2:value>None</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>criticalFullfillment</m2:name>
                              <m2:value>No</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>deviceID</m2:name>
                              <m2:value>Id</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>dropShipDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>RMA</m2:name>
                              <m2:value>N</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderNumber</m2:name>
                              <m2:value>Number</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>sapOrderStatus</m2:name>
                              <m2:value>Unknown</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shipmentType</m2:name>
                              <m2:value>G</m2:value>
                            </m2:attribute>
                            <m2:attribute>
                              <m2:name>shippingDate</m2:name>
                              <m2:value>07/04/2015</m2:value>
                            </m2:attribute>
                          </m2:attributeList>
                        </m2:component>
                      </m2:componentList>
                    </m2:component>
                  </m2:componentList>
                </m2:product>
              </m2:productList>
              <m2:nonProductCatalogDataList>
                <m2:nonProductCatalogData>
                  <m2:name>departmentName</m2:name>
                  <m2:value>MW Cons U-verse B.O</m2:value>
                </m2:nonProductCatalogData>
                <m2:nonProductCatalogData>
                  <m2:name>departmentPhone</m2:name>
                  <m2:value>8885444805</m2:value>
                </m2:nonProductCatalogData>
              </m2:nonProductCatalogDataList>
            </m2:orderActionInfo>
          </m2:orderActionInfoList>
          <m2:customerInfoList>
            <m2:customerInfo>
              <m2:accountId>${ban}</m2:accountId>
              <m2:currentCustomerIndicator>true</m2:currentCustomerIndicator>
              <m2:name>SheldonCooper</m2:name>
              <m2:type>I</m2:type>
              <m2:subType>R</m2:subType>
              <m2:UBIndicator>false</m2:UBIndicator>
              <m2:classOfService>Residential</m2:classOfService>
              <m2:legalEntity>AM00</m2:legalEntity>
              <m2:creditRiskClass>Low</m2:creditRiskClass>
              <m2:timeZoneOffset>-5</m2:timeZoneOffset>
              <m2:billCycle>26</m2:billCycle>
              <m2:billRound>25</m2:billRound>
              <m2:customerInfoContactList>
                <m2:customerInfoContact>
                  <m2:contactType>CU</m2:contactType>
                  <m2:firstName>Sheldon</m2:firstName>
                  <m2:lastName>Cooper</m2:lastName>
                  <m2:phoneNumber>1234567890</m2:phoneNumber>
                  <m2:secondaryPhoneNumber>9876543210</m2:secondaryPhoneNumber>
                </m2:customerInfoContact>
              </m2:customerInfoContactList>
            </m2:customerInfo>
          </m2:customerInfoList>
        </m2:order>
      </m2:transactionInfo>
    </m2:bbnmsOrder>
  </SOAP-ENV:Body>
</SOAP-ENV:Envelope>